GET http://localhost:8080/customers

GET http://localhost:8080/orders

GET http://localhost:8080/stocks

GET http://localhost:8080/products

PUT http://localhost:8080/customers/{id}
Content-Type: application/json

{
  "customerName": "Updated Name",
  "address": "Updated Address",
  "phoneNumber": "1234567890"
}

DELETE http://localhost:8080/orders/{orderId}
